package in.mapmytour.blog.controller;

import in.mapmytour.blog.dto.APIResponse;
import in.mapmytour.blog.dto.request.blogpost.TranslateRequest;
import in.mapmytour.blog.dto.response.blogpost.TranslateResponse;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import jakarta.validation.Valid;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.client.RestClient;

import java.net.URLEncoder;
import java.net.URLDecoder;
import java.nio.charset.StandardCharsets;
import java.text.Normalizer;
import java.util.ArrayList;
import java.util.List;
import java.util.Set;

@RestController
@RequestMapping("/api/v1/blog/translate")
@RequiredArgsConstructor
@Slf4j
public class TranslateController {

    private static final String DISCLAIMER =
            "⚠️ Auto-generated by AI (Google Translate). This translation may contain inaccuracies. "
                    + "The authoritative source is the original-language article above. MapMyTimes is not liable for translation errors. "
                    + "For journalism of integrity, please refer to the article in its original language.";

    private static final Set<String> ALLOWED = Set.of("en", "hi");

    private static final String CONTEXT_PREFIX_EN_TO_HI =
            "T: Translate ONLY to DAY-TO-DAY GENERAL HINDI (spoken news-style, NOT Sanskritized/bookish Hindi). 4 Rules: (1) Use everyday common words like ज़्यादा, बढ़िया, हंगामा, निराश, हालांकि; NEVER use formal अधिक, उत्तम, अव्यवस्था, किन्तु, यद्यपि. (2) Keep English loanwords (Tour, Highlights, Tips, Budget, Golden Triangle, Hotel, Fort, Temple, Flight, Train, Road, Market, Food, Guide, City, Village) unchanged — don't translate them to long Sanskrit synonyms. (3) Keep ALL place-names verbatim. (4) Output must be valid Unicode Devanagari UTF-8. ";

    private static final String CONTEXT_PREFIX_HI_TO_EN =
            "T: Simple natural English (Indian news style). Keep place-names unchanged. ";

    private static final String[][] HINDI_AAM_GLOSSARY = {
            {"शीर्ष", "टॉप"}, {"मुख्य आकर्षण", "हाइलाइट्स"}, {"आकर्षण", "हाइलाइट्स"},
            {"अन्वेषण", "देखें"}, {"खोज", "सर्च"}, {"यात्रा", "टूर"}, {"भ्रमण", "टूर"},
            {"प्रसिद्ध", "फेमस"}, {"जाना माना", "फेमस"}, {"विख्यात", "फेमस"},
            {"स्थानीय", "लोकल"}, {"स्थानीय भोजन", "लोकल फूड"},
            {"सुझाव", "टिप्स"}, {"यात्रा सुझाव", "ट्रैवल टिप्स"}, {"युक्तियाँ", "टिप्स"}, {"युक्ति", "टिप"},
            {"बजट विभाजन", "बजट ब्रेकडाउन"}, {"विभाजन", "ब्रेकडाउन"},
            {"परिचय", "इंट्रो"}, {"निष्कर्ष", "कन्क्लूजन"}, {"सर्वोत्तम", "बेस्ट"},
            {"सर्किट", "सर्किट"}, {"स्मारक", "मोनुमेंट"}, {"किलों", "फोर्ट्स"}, {"किला", "फोर्ट"}, {"किले", "फोर्ट्स"},
            {"मंदिर", "टेम्पल"}, {"समुद्री", "बीच"}, {"तट", "बीच"},
            {"राष्ट्रीय उद्यान", "नेशनल पार्क"}, {"उद्यान", "पार्क"},
            {"आरक्षण", "बुकिंग"}, {"बुक", "बुकिंग"},
            {"आवास", "होटल"}, {"विश्राम गृह", "गेस्टहाउस"},
            {"परिवहन", "ट्रांसपोर्ट"}, {"सार्वजनिक परिवहन", "पब्लिक ट्रांसपोर्ट"},
            {"रेलगाड़ी", "ट्रेन"}, {"हवाई जहाज", "फ्लाइट"}, {"विमान", "फ्लाइट"},
            {"सड़क", "रोड"}, {"मार्ग", "रूट"}, {"मार्गदर्शक", "गाइड"},
            {"प्रस्तावना", "इंट्रो"}, {"अनुशंसा", "रिकमेंडेशन"},
            {"अनुभव", "एक्सपीरियंस"}, {"अद्भुत", "अमेजिंग"}, {"बहुत सुंदर", "बेहतरीन"},
            {"समय", "टाइम"}, {"घूमने का सबसे अच्छा समय", "बेस्ट टाइम टू विज़िट"},
            {"संगमरमर की चमक", "संगमरमर की चमक"}, {"संगमरमरी आवरण", "संगमरमर की चमक"}, {"संगमरमरी चमक", "संगमरमर की चमक"},
            {"पुरानी दिल्ली की अराजकता", "ओल्ड दिल्ली का हंगामा"}, {"पुरानी दिल्ली की अव्यवस्था", "ओल्ड दिल्ली का हंगामा"},
            {"बलुआ पत्थर की चमक", "गुलाबी बलुआ पत्थर की चमक"},
            {"अधिक बार", "कई बार"}, {"कई गिनती", "बहुत बार"}, {"कम गिनती", "कम बार"}, {"गिनती से अधिक बार", "कई सालों से"},
            {"परिणाम देना बंद नहीं करता", "कभी भी निराश नहीं करता"}, {"परिणाम देना बंद", "मज़ा लेना बंद"},
            {"अव्यवस्था", "हंगामा"}, {"अराजकता", "हंगामा"}, {"अव्यवस्थित", "बिखरा हुआ"},
            {"प्रसिद्ध स्थानीय बाज़ार", "फेमस लोकल मार्केट"}, {"प्रसिद्ध स्थानीय बाजार", "फेमस लोकल मार्केट"},
            {"स्थानीय व्यंजन", "लोकल फूड"}, {"प्रसिद्ध स्थानीय भोजन", "फेमस लोकल फूड"},
            {"कैसे पहुंचें", "हाउ टू रीच"}, {"टॉप चीज़ें करने योग्य", "टॉप थिंग्स टू डू"},
            {"करने योग्य शीर्ष चीज़ें", "टॉप थिंग्स टू डू"},
            {"संपर्क", "कॉन्टैक्ट"}, {"शिकायत", "कंप्लेंट"},
            {"जानकारी", "इन्फो"}, {"विवरण", "डिटेल्स"}, {"विस्तृत", "विस्तृत"},
            {"अपडेट", "अपडेट"}, {"समाचार", "न्यूज"}, {"खबर", "न्यूज"},
            {"सुरक्षित", "सेफ"}, {"खतरनाक", "संकटमय"}, {"सावधान", "केयरफुल"},
            {"स्वास्थ्य", "हेल्थ"}, {"खाना", "फूड"}, {"भोजन", "फूड"},
            {"पानी", "वॉटर"}, {"रेस्तरां", "रेस्टोरेंट"}, {"धावा", "ढाबा"},
            {"दुकान", "शॉप"}, {"बाज़ार", "मार्केट"}, {"बाजार", "मार्केट"}, {"शहर", "सिटी"},
            {"गाँव", "विलेज"}, {"देश", "कंट्री"}, {"विदेश", "फॉरेन"},
            {"आयोजन", "इवेंट"}, {"कार्यक्रम", "शेड्यूल"},
            {"भविष्यवाणी", "फोरकास्ट"}, {"आज का मौसम", "वेदर"},
            {"मौसम", "वेदर"}, {"तापमान", "टेम्प्रेचर"},
            {"अनुमानित", "अप्रॉक्स"}, {"लगभग", "अराउंड"},
            {"कई", "बहुत सारे"}, {"कुछ", "कुछ"},
            {"अधिक", "ज़्यादा"}, {"अधिकतर", "ज़्यादातर"}, {"अधिकांश", "ज़्यादातर"},
            {"न्यून", "कम"}, {"न्यूनतम", "कम से कम"}, {"अधिकतम", "ज़्यादा से ज़्यादा"},
            {"शीघ्र", "जल्दी"}, {"जल्दी से", "जल्दी जल्दी"},
            {"किंतु", "पर"}, {"यद्यपि", "हालाँकि"},
            {"इसलिए", "इसलिए"}, {"फलस्वरूप", "इस वजह से"},
            {"अतः", "तो"}, {"परन्तु", "पर"},
            {"शीघ्र", "जल्दी"}, {"धीरे", "स्लो"}, {"वेग से", "फास्ट"},
            {"कभी कभी", "कभी कभी"}, {"कभी नहीं", "कभी नहीं"}, {"प्रायः", "अक्सर"}, {"अधिकांशतः", "ज़्यादातर"},
            {"पहले", "पहले"}, {"बाद", "बाद"}, {"साथ ही", "साथ ही"}, {"इसके अलावा", "इसके अलावा"},
            {"देखा", "देखा"}, {"किया", "किया"}, {"चलाया", "किया"}, {"किया गया", "हो गया"}, {"बनाया", "बनाया"},
            {"अच्छा", "बढ़िया"}, {"बहुत अच्छा", "बढ़िया"}, {"सुंदर", "प्यारा"}, {"बहुत सुंदर", "बेहतरीन"},
            {"निःशुल्क", "फ्री"}, {"मुफ्त", "फ्री"},
            {"शुल्क", "फीस"}, {"चार्ज", "चार्ज"},
            {"कीमत", "प्राइस"}, {"मूल्य", "प्राइस"}, {"दाम", "रेट"},
            {"निश्चित", "फिक्स्ड"}, {"अनिश्चित", "टेंटेटिव"},
            {"विचार", "थॉट"}, {"राय", "अपिनियन"}, {"मत", "व्यू"},
            {"लक्ष्य", "गोल"}, {"उद्देश्य", "प्लान"}, {"योजना", "प्लान"},
            {"प्रबंधन", "मैनेजमेंट"}, {"विकास", "ग्रोथ"},
            {"अनुरोध", "रिक्वेस्ट"}, {"सहायता", "सपोर्ट"}, {"मदद", "हेल्प"},
            {"आसानी से", "आसानी से"}, {"मुश्किल से", "मुश्किल से"}, {"जल्दी से", "जल्दी"},
            {"बाहर", "बाहर"}, {"अंदर", "अंदर"}, {"पास", "पास"}, {"दूर", "दूर"}, {"आगे", "आगे"}, {"पीछे", "पीछे"},
            {"दोपहर", "दोपहर"}, {"सुबह", "सुबह"}, {"शाम", "शाम"}, {"रात", "रात"}
    };

    private final ObjectMapper objectMapper;

    @Value("${mapmytimes.translate.endpoint:https://translate.googleapis.com/translate_a/single}")
    private String endpoint;

    private final RestClient restClient = RestClient.builder().build();

    @GetMapping
    public ResponseEntity<APIResponse<TranslateResponse>> translateGetFallback() {
        return ResponseEntity.status(HttpStatus.METHOD_NOT_ALLOWED).body(APIResponse.<TranslateResponse>builder()
                .success(false)
                .statusCode(HttpStatus.METHOD_NOT_ALLOWED.value())
                .message("Translate endpoint requires a POST request with JSON body: {sourceLang, targetLang, items:[{id,text}]}")
                .build());
    }

    @PostMapping
    public ResponseEntity<APIResponse<TranslateResponse>> translate(@Valid @RequestBody TranslateRequest request) {
        String src = normalize(request.getSourceLang());
        String tgt = normalize(request.getTargetLang());

        if (!ALLOWED.contains(src) || !ALLOWED.contains(tgt)) {
            return ResponseEntity.badRequest().body(APIResponse.<TranslateResponse>builder()
                    .success(false)
                    .statusCode(HttpStatus.BAD_REQUEST.value())
                    .message("Unsupported language pair. Only 'en' and 'hi' are allowed.")
                    .build());
        }

        if (src.equals(tgt)) {
            List<TranslateResponse.Item> same = request.getItems().stream()
                    .map(it -> TranslateResponse.Item.builder()
                            .id(it.getId())
                            .source(it.getText())
                            .translated(it.getText())
                            .build())
                    .toList();
            return ResponseEntity.ok(APIResponse.<TranslateResponse>builder()
                    .success(true)
                    .statusCode(HttpStatus.OK.value())
                    .message("Source and target same; returned original text.")
                    .data(TranslateResponse.builder()
                            .sourceLang(src)
                            .targetLang(tgt)
                            .items(same)
                            .disclaimer(DISCLAIMER)
                            .translated(false)
                            .build())
                    .build());
        }

        List<TranslateResponse.Item> out = new ArrayList<>(request.getItems().size());
        try {
            String prefix = "en".equals(src) && "hi".equals(tgt) ? CONTEXT_PREFIX_EN_TO_HI
                    : "hi".equals(src) && "en".equals(tgt) ? CONTEXT_PREFIX_HI_TO_EN : "";
            String nano = Long.toHexString(System.nanoTime()) + Long.toHexString(System.currentTimeMillis());
            String openWrap = "XXBEGINXX" + nano + "XXBEGXX";
            String closeWrap = "XXENDXX" + nano + "XXENX";
            String prefixWrap = openWrap; // not used for wrapping; use open/close
            for (TranslateRequest.Item it : request.getItems()) {
                String original = it.getText();
                if (original == null || original.isBlank()) {
                    out.add(TranslateResponse.Item.builder()
                            .id(it.getId())
                            .source(original)
                            .translated(original)
                            .build());
                    continue;
                }
                String toSend = prefix + openWrap + original + closeWrap;
                String encoded = URLEncoder.encode(toSend, StandardCharsets.UTF_8);
                String url = endpoint
                        + "?client=gtx&sl=" + src + "&tl=" + tgt + "&dt=t&q=" + encoded;
                try {
                    String raw = restClient.get().uri(url).retrieve().body(String.class);
                    String translated = parseTranslation(raw, openWrap, closeWrap);
                    if (translated == null || translated.isBlank()) translated = original;
                    if ("hi".equals(tgt)) {
                        translated = sanitizeDevanagari(translated);
                        translated = applyHindiGlossary(translated);
                        translated = normalizeHindiPunctuation(translated);
                        translated = sanitizeDevanagari(translated);
                    }
                    out.add(TranslateResponse.Item.builder()
                            .id(it.getId())
                            .source(original)
                            .translated(translated)
                            .build());
                } catch (Exception ex) {
                    log.warn("Translate single item failed id={}: {}", it.getId(), ex.getMessage());
                    out.add(TranslateResponse.Item.builder()
                            .id(it.getId())
                            .source(original)
                            .translated(original)
                            .build());
                }
            }

            return ResponseEntity.ok(APIResponse.<TranslateResponse>builder()
                    .success(true)
                    .statusCode(HttpStatus.OK.value())
                    .message("Translation complete")
                    .data(TranslateResponse.builder()
                            .sourceLang(src)
                            .targetLang(tgt)
                            .items(out)
                            .disclaimer(DISCLAIMER)
                            .translated(true)
                            .build())
                    .build());
        } catch (Exception e) {
            log.error("Translate request failed", e);
            return ResponseEntity.status(HttpStatus.BAD_GATEWAY).body(APIResponse.<TranslateResponse>builder()
                    .success(false)
                    .statusCode(HttpStatus.BAD_GATEWAY.value())
                    .message("Translation service temporarily unavailable. Showing original-language content.")
                    .build());
        }
    }

    private String parseTranslation(String raw, String openWrap, String closeWrap) {
        if (raw == null || raw.isBlank()) return null;
        try {
            JsonNode root = objectMapper.readTree(raw);
            if (!root.isArray() || root.isEmpty()) return null;
            JsonNode first = root.get(0);
            if (!first.isArray()) return null;
            StringBuilder sb = new StringBuilder();
            for (JsonNode seg : first) {
                if (seg.isArray() && seg.size() > 0) {
                    JsonNode w = seg.get(0);
                    if (w != null && !w.isNull()) sb.append(w.asText());
                }
            }
            String s = sb.toString();
            if (s.isBlank()) return null;
            String out = safeDecode(s);

            if (openWrap != null && !openWrap.isEmpty()) {
                int p = out.indexOf(openWrap);
                // Search lower-case / space-padded variants too (Google may insert spaces)
                if (p < 0) {
                    String lo = out.toLowerCase();
                    String owLo = openWrap.toLowerCase();
                    String cwLo = (closeWrap != null ? closeWrap : "").toLowerCase();
                    int pl = lo.indexOf(owLo);
                    if (pl >= 0) p = pl;
                }
                if (p >= 0) out = out.substring(p + openWrap.length());
                else {
                    // Try extracting from hex core: take 16-char hex from openWrap, find index in out (case-insensitive)
                    String core = openWrap.replaceAll("^[A-Z0-9]+", "").replaceAll("[A-Z0-9]+$", "");
                    if (core.length() >= 10) {
                        int idx = out.toLowerCase().indexOf(core.toLowerCase());
                        if (idx >= 0) out = out.substring(idx + core.length() + ("XXBEGXX").length());
                    }
                }
            }
            if (closeWrap != null && !closeWrap.isEmpty()) {
                int q = out.lastIndexOf(closeWrap);
                if (q < 0) {
                    String lo = out.toLowerCase();
                    String cwLo = closeWrap.toLowerCase();
                    int ql = lo.lastIndexOf(cwLo);
                    if (ql >= 0) q = ql;
                }
                if (q >= 0) out = out.substring(0, q);
                else {
                    String core = closeWrap.replaceAll("^[A-Z0-9]+", "").replaceAll("[A-Z0-9]+$", "");
                    if (core.length() >= 10) {
                        int idx = out.toLowerCase().lastIndexOf(core.toLowerCase());
                        if (idx >= 0) out = out.substring(0, idx - ("XXENDXX").length());
                    }
                }
            }
            out = out.trim();
            // Devanagari combining-matra edge: if first char is a pure combining mark, prepend 'अ' as base consonant fallback.
            if (!out.isEmpty()) {
                char f = out.charAt(0);
                if ((f >= '\u0900' && f <= '\u0903') || (f >= '\u093A' && f <= '\u094F') || (f >= '\u0951' && f <= '\u0954') || (f >= '\u0962' && f <= '\u0963')) {
                    out = "अ" + out;
                }
            }
            return out.isEmpty() ? null : out;
        } catch (Exception e) {
            log.warn("Parse translation failed: {}", e.getMessage());
            return null;
        }
    }

    private String sanitizeDevanagari(String text) {
        if (text == null || text.isEmpty()) return text;
        String out = Normalizer.isNormalized(text, Normalizer.Form.NFC) ? text : Normalizer.normalize(text, Normalizer.Form.NFC);
        out = out
                .replace("\u200D", "")
                .replace("\u200C", "")
                .replace("\u200B", "")
                .replace("\u00AD", "")
                .replace("\uFEFF", "")
                .replace("\u2060", "");
        StringBuilder sb = new StringBuilder(out.length());
        boolean lastWasBase = false;
        boolean inCluster = false;
        for (int i = 0; i < out.length(); i++) {
            char c = out.charAt(i);
            if (Character.isHighSurrogate(c)) {
                sb.append(c);
                if (i + 1 < out.length()) {
                    sb.append(out.charAt(i + 1));
                    i++;
                }
                lastWasBase = true;
                inCluster = false;
                continue;
            }
            int cp = c;
            boolean isDevanagariIndependentVowel = (cp >= 0x0904 && cp <= 0x0914) || cp == 0x0905 || cp == 0x0906 || cp == 0x0907 || cp == 0x0908 || cp == 0x0909 || cp == 0x090A || cp == 0x090B || cp == 0x090C || cp == 0x090F || cp == 0x0910 || cp == 0x0913 || cp == 0x0914;
            boolean isDevanagariConsonant = (cp >= 0x0915 && cp <= 0x0939);
            boolean isDependentVowelSign = (cp >= 0x093A && cp <= 0x094F) || cp == 0x0955 || cp == 0x0956 || cp == 0x0957 || cp == 0x0962 || cp == 0x0963;
            boolean isSpacingSign = (cp >= 0x0900 && cp <= 0x0903) || cp == 0x0951 || cp == 0x0952 || cp == 0x0953 || cp == 0x0954;
            boolean isVirama = cp == 0x094D;
            boolean isNukta = cp == 0x093C;
            boolean isAnyDevanagariAccent = (cp >= 0x0900 && cp <= 0x0963) && !(isDevanagariConsonant || isDevanagariIndependentVowel);
            boolean isCombining = isDependentVowelSign || isSpacingSign || isVirama || isNukta;
            if (isCombining && !lastWasBase && !inCluster) {
                // Only prepend 'अ' if at absolute word-beginning (no preceding syllable)
                if (sb.length() == 0 || Character.isWhitespace(sb.charAt(sb.length() - 1))) {
                    sb.append('अ');
                } else {
                    // Drop dangling combining marks mid-sentence unless nukta after consonant
                    continue;
                }
            }
            sb.append(c);
            if (isDevanagariConsonant || isDevanagariIndependentVowel) {
                inCluster = true;
                lastWasBase = true;
            } else if (isVirama) {
                // After halant, next consonant makes conjunct, so lastWasBase=false for next conjunct, set true for next combining matra
                inCluster = true;
                lastWasBase = true;
            } else if (isCombining) {
                // After nukta/matra/anusvara/visarga/vowel-sign: cluster is COMPLETE base syllable, accepts further matras/accents
                inCluster = true;
                lastWasBase = true;
            } else if (cp == ' ' || cp == '\t' || cp == '\n' || cp == '\r') {
                inCluster = false;
                lastWasBase = false;
            } else {
                inCluster = false;
                lastWasBase = false;
            }
        }
        String s = sb.toString();
        // Remove stray अ inserted between consonant + combining mark in clusters
        s = s.replaceAll("([\\u0915-\\u0939\\u0904-\\u0914])(\\u0905+)([\\u093A-\\u094F\\u0962\\u0963\\u0902\\u0903])", "$1$3");
        s = s.replaceAll("([\\u093A-\\u094F\\u0902\\u0903])(\\u0905+)([\\u093A-\\u094F\\u0902\\u0903])", "$1$3");
        // Drop stray isolated nukta after non-devanagari
        s = s.replaceAll("([^\\u0900-\\u097F])\u093C", "$1");
        s = s.replaceAll("(?<![\\u0915-\\u0939])\u094D(?![\\u0915-\\u0939])", "");
        // Collapse duplicate identical Devanagari matras / spacing marks
        s = s.replaceAll("([\\u0902\\u0903\\u093C\\u093E-\\u094F\\u0951-\\u0954])\\1+", "$1");
        // Remove stray अ inside हिंदी words (between a consonant-vowel cluster and another accent/nukta)
        s = s.replaceAll("([\\u0915-\\u0939][\\u093A-\\u094F]?)(\\u0905)([\\u0902\\u0903\\u093C\\u093A-\\u094F])", "$1$3");
        // Remove stray अ right after a base consonant that already has a vowel sign (between स्वर/व्यंजन cluster + extra)
        s = s.replaceAll("([\\u0904-\\u0939][\\u0900-\\u0954]?)(\\u0905)(?=[\\u0900-\\u0954])", "$1");
        // Remove stray standalone अ between consonant + nukta/anusvara (Google inserts these)
        s = s.replaceAll("([\\u0915-\\u0939])\\u0905([\\u093C\\u0902\\u0903])", "$1$2");
        s = s.replaceAll(" +", " ")
                .trim();
        return s;
    }

    private String applyHindiGlossary(String text) {
        if (text == null || text.isEmpty()) return text;
        String out = text;
        for (String[] pair : HINDI_AAM_GLOSSARY) {
            if (pair.length < 2 || pair[0].isEmpty()) continue;
            out = out.replace(pair[0], pair[1]);
        }
        return out;
    }

    private String normalizeHindiPunctuation(String text) {
        if (text == null || text.isEmpty()) return text;
        return text
                .replace("।", "।")
                .replace(",", ",")
                .replaceAll("([,])+", ",")
                .replaceAll("([।])+", "।")
                .replaceAll("([!])+", "!")
                .replaceAll("([?])+", "?")
                .replaceAll("(\\.){3,}", "…")
                .replaceAll("\\s+([,;:.!?।])", "$1")
                .replaceAll("([\"'“”])\\s+([,;:.!?।])", "$1$2")
                .replaceAll("\\s+", " ")
                .trim();
    }

    private String safeDecode(String encoded) {
        if (encoded == null || encoded.isBlank()) return encoded;
        String out = encoded
                .replace("%3ए", ":").replace("%3aे", ":")
                .replace("%3A", ":").replace("%3a", ":")
                .replace("%2सी", ",").replace("%2cी", ",").replace("%2Cी", ",")
                .replace("%2C", ",").replace("%2c", ",")
                .replace("%26", "&").replace("%20", " ")
                .replace("%3B", ";").replace("%3b", ";")
                .replace("%3F", "?").replace("%3f", "?")
                .replace("%2F", "/").replace("%2f", "/")
                .replace("%28", "(").replace("%29", ")")
                .replace("%21", "!").replace("%22", "\"")
                .replace("%27", "'").replace("%60", "`")
                .replace("%2B", "+").replace("%2b", "+")
                .replace("%3D", "=").replace("%3d", "=")
                .replace("%24", "$").replace("%40", "@").replace("%23", "#")
                .replace("%25", "%").replace("%5B", "[").replace("%5b", "[")
                .replace("%5D", "]").replace("%5d", "]")
                .replace("%7B", "{").replace("%7D", "}")
                .replace("%3C", "<").replace("%3E", ">")
                .replace("%C2%AB", "«").replace("%c2%ab", "«")
                .replace("%C2%BB", "»").replace("%c2%bb", "»")
                .replace("%E2%80%93", "–").replace("%E2%80%94", "—")
                .replace("%E2%80%98", "‘").replace("%E2%80%99", "’")
                .replace("%E2%80%9C", "“").replace("%E2%80%9D", "”")
                .replace("%E2%80%A6", "…")
                .replace("&amp;", "&").replace("&lt;", "<").replace("&gt;", ">")
                .replace("&quot;", "\"").replace("&#39;", "'").replace("&apos;", "'")
                .replace("&#x27;", "'").replace("&#x2F;", "/").replace("&#38;", "&")
                .replace("&#x3D;", "=").replace("&#x22;", "\"").replace("&#x3C;", "<")
                .replace("&#x3E;", ">").replace("&#x26;", "&").replace("&#x20;", " ");
        for (int i = 0; i < 3; i++) {
            try {
                String next = URLDecoder.decode(out, StandardCharsets.UTF_8);
                if (next.equals(out)) break;
                out = next;
            } catch (Exception e) { break; }
        }
        return out;
    }

    private static String normalize(String s) {
        if (s == null) return "";
        s = s.trim().toLowerCase();
        if (s.length() > 2) s = s.substring(0, 2);
        return s;
    }
}
