package in.mapmytour.auth.dto.user;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDate;

@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class TravelGroupRequest {
    @NotBlank(message = "Group name is required")
    private String name;

    private String description;

    @NotBlank(message = "Destination is required")
    private String destination;

    @NotNull(message = "Travel date is required")
    private LocalDate travelDate;

    private LocalDate returnDate;

    private Integer maxMembers;

    private String travelType; // SOLO, GROUP, FAMILY, COUPLE

    private Boolean isPublic;

    /**
     * Optional URL of the group image/profile picture.
     * Typically an S3 or CDN URL generated by the frontend or another service.
     */
    private String imageUrl;
}

