ALTER TABLE blog_posts
    ADD COLUMN IF NOT EXISTS reading_time INTEGER,
    ADD COLUMN IF NOT EXISTS featured_image TEXT,
    ADD COLUMN IF NOT EXISTS content_blocks TEXT,
    ADD COLUMN IF NOT EXISTS table_of_contents TEXT,
    ADD COLUMN IF NOT EXISTS travel_meta TEXT,
    ADD COLUMN IF NOT EXISTS seo TEXT,
    ADD COLUMN IF NOT EXISTS visibility VARCHAR(32) NOT NULL DEFAULT 'PUBLIC',
    ADD COLUMN IF NOT EXISTS language VARCHAR(16) NOT NULL DEFAULT 'en',
    ADD COLUMN IF NOT EXISTS view_count BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS share_count BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS bookmark_count BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS scheduled_at TIMESTAMP NULL,
    ADD COLUMN IF NOT EXISTS is_featured BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS is_trending BOOLEAN NOT NULL DEFAULT FALSE;

